"use client";

import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';
import { Order, getAllOrdersAPI } from '@/lib/api';

type OrderContextType = {
  orders: Order[];
  reloadOrders: () => Promise<void>;
  updateOrderState: (poNumber: string, updates: Partial<Order>) => void;
  existingPoNumbers: string[];
};

const OrderContext = createContext<OrderContextType | undefined>(undefined);

export function OrderProvider({ children }: { children: React.ReactNode }) {
  const [orders, setOrders] = useState<Order[]>([]);
  const [existingPoNumbers, setExistingPoNumbers] = useState<string[]>([]);

  const reloadOrders = useCallback(async () => {
    const fetched = await getAllOrdersAPI();
    setOrders(fetched);
    // Keep the PO number blocklist in sync automatically
    setExistingPoNumbers(fetched.map(o => o.poNumber));
  }, []);

  useEffect(() => {
    const autoClearOnInit = async () => {
      if (typeof window !== 'undefined') {
        const cleared = localStorage.getItem('sasons_init_cleared');
        if (!cleared) {
          localStorage.removeItem("savedOrders");
          localStorage.removeItem("bomCalculationDraft");
          localStorage.removeItem("autoGeneratedProcurementRequests");
          localStorage.removeItem("preStitchedInventory");
          localStorage.removeItem("systemLogs");
          localStorage.removeItem("archivedProcurementRequests");
          localStorage.setItem("orders_cleared", "true");

          try {
            const BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL || "http://127.0.0.1:5000";
            const WRITE_KEY = process.env.NEXT_PUBLIC_ERP_WRITE_API_KEY as string;
            await fetch(`${BACKEND_URL}/api/reset-database`, {
              method: "POST",
              headers: { "X-API-Key": WRITE_KEY }
            });
          } catch (e: any) {
            console.warn("Auto-reset of database skipped (backend server may be offline).");
          }

          localStorage.setItem('sasons_init_cleared', 'true');
          window.dispatchEvent(new Event('storage'));
        }
      }
      reloadOrders();
    };

    autoClearOnInit();

    // ✅ Listen to the custom orders-updated event (fired after every successful saveOrderAPI call)
    const handleOrdersUpdated = () => {
      reloadOrders();
    };

    // ✅ Also listen to native storage event for cross-tab sync
    const handleStorageChange = (e: StorageEvent) => {
      if (e.key === 'savedOrders' || e.key === null) {
        reloadOrders();
      }
    };

    window.addEventListener('orders-updated', handleOrdersUpdated);
    window.addEventListener('storage', handleStorageChange);

    return () => {
      window.removeEventListener('orders-updated', handleOrdersUpdated);
      window.removeEventListener('storage', handleStorageChange);
    };
  }, [reloadOrders]);

  const updateOrderState = (poNumber: string, updates: Partial<Order>) => {
    setOrders(prev => {
      const updated = prev.map(o => o.poNumber === poNumber ? { ...o, ...updates } : o);
      localStorage.setItem('savedOrders', JSON.stringify(updated));
      window.dispatchEvent(new Event('storage'));
      return updated;
    });
  };

  return (
    <OrderContext.Provider value={{ orders, reloadOrders, updateOrderState, existingPoNumbers }}>
      {children}
    </OrderContext.Provider>
  );
}

export function useOrders() {
  const context = useContext(OrderContext);
  if (!context) {
    throw new Error('useOrders must be used within an OrderProvider');
  }
  return context;
}
