"use client";


import React, { useState, useEffect } from 'react';
import {
  Truck,
  Clock,
  FileCheck,
  AlertTriangle,
  DollarSign,
  Search,
  Filter,
  Plus,
  Eye,
  Package,
  X,
  CheckCircle2,
  AlertCircle,
  ChevronLeft,
  ChevronRight,
  ShieldAlert,
  Building2,
  Mail,
  Phone,
  ListChecks,
  Star,
  ArrowRight,
  Download,
  Upload,
  FileUp
} from 'lucide-react';
import { useRouter } from 'next/navigation';
import ProcurementStepper from '@/components/ProcurementStepper';
import { useTranslation } from '@/hooks/useTranslation';
import { useAuth } from '@/context/AuthContext';
import { updateOrderAndLog } from '@/lib/logger';
import { useOrders } from '@/contexts/order-context';
import { isStageMatch } from '@/utils/orderUtils';
import { formatDateDisplay } from '@/utils/dateUtils';
import { generateProcurementPDF } from '@/utils/pdfGenerator';

const initialMockShortages: any[] = [];




const timelineSteps = [
  { label: 'Request Created', date: 'May 10, 10:30 AM', completed: true },
  { label: 'Approved', date: 'May 11, 09:15 AM', completed: true },
  { label: 'Ordered', date: 'May 11, 02:45 PM', completed: true },
  { label: 'In Transit', date: 'May 13, 08:00 AM', completed: true },
  { label: 'Delivered', date: 'Expected May 14', completed: false },
];

const STORE_ARTICLES = "Store's Article";

export default function ProcurementPage() {
  const router = useRouter();
  const { user } = useAuth();
  const { orders } = useOrders();

  const advanceStage = async (nextPath: string, nextStage: string) => {
    if (typeof window === 'undefined') return;
    const params = new URLSearchParams(window.location.search);
    const po = params.get('poNumber');
    if (po) {
      try {
        const BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL || "http://localhost:5000";
        const res = await fetch(`${BACKEND_URL}/purchase_orders/update_stage`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ poNumber: po, stage: nextStage })
        });

        if (res.ok) {
          // Log legacy UI helper
          updateOrderAndLog(po, user?.name || 'System User', 'Updated', `Advanced to ${nextStage}`, (orders) => {
            return orders.map((o: any) => o.poNumber === po ? { ...o, stage: nextStage } : o);
          });
          window.dispatchEvent(new Event("orders-updated"));
          router.push(`${nextPath}?poNumber=${encodeURIComponent(po)}`);
        } else {
          alert("Failed to advance stage on the server.");
        }
      } catch (err) {
        console.error("Failed to advance stage:", err);
        alert("Failed to reach server.");
      }
    } else {
      router.push(nextPath);
    }
  };

  const { t } = useTranslation();
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState('All');
  const [priorityFilter, setPriorityFilter] = useState('All');
  const [supplierFilter, setSupplierFilter] = useState<string[]>([]);
  const [isSupplierDropdownOpen, setIsSupplierDropdownOpen] = useState(false);
  const [suppliersList, setSuppliersList] = useState<any[]>([]);
  const [selectedSupplierFilter, setSelectedSupplierFilter] = useState<any>(null);
  const [supplierSearchTerm, setSupplierSearchTerm] = useState('');
  const [selectedSuppliers, setSelectedSuppliers] = useState<Record<string, string>>({});

  const [mockShortages, setMockShortages] = useState<any[]>([]);
  const [poInput, setPoInput] = useState('');
  const [archivedRequests, setArchivedRequests] = useState<any[]>([]);
  const [suppliers, setSuppliers] = useState<any[]>([]);

  // Multi-Supplier Selection State
  const [selectedRowIds, setSelectedRowIds] = useState<Set<string>>(new Set());
  const [orderQuantities, setOrderQuantities] = useState<Record<string, number | string>>({});
  const [articleSplits, setArticleSplits] = useState<{ id: string, parentId: string }[]>([]);


  // Interactive Navigator State
  const [activeTab, setActiveTab] = useState<'pending' | 'in_process' | 'completed' | 'history'>('pending');

  const [inProcessPOs, setInProcessPOs] = useState<any[]>([]);
  const [completedPOs, setCompletedPOs] = useState<any[]>([]);
  const [historyPOs, setHistoryPOs] = useState<any[]>([]);
  const [allocatedItems, setAllocatedItems] = useState<any[]>([]);
  const [editModeSupplier, setEditModeSupplier] = useState<string | null>(null);
  const [showAllocatedModal, setShowAllocatedModal] = useState(false);

  React.useEffect(() => {
    localStorage.removeItem('procurement_requests');
    localStorage.removeItem('purchase_orders');
    localStorage.removeItem('sharedPurchaseOrders');
    localStorage.removeItem('procurement_draft_pos');
    localStorage.removeItem('review_po_session');
    localStorage.removeItem('autoGeneratedProcurementRequests');
  }, []);

  React.useEffect(() => {
    const loadSharedOrders = () => {
      const storedAllocated = localStorage.getItem('allocatedProcurementItems');
      if (storedAllocated) {
        try {
          setAllocatedItems(JSON.parse(storedAllocated));
        } catch (e) { }
      }

      const stored = localStorage.getItem('sharedPurchaseOrders');
      if (stored) {
        try {
          const parsed = JSON.parse(stored);
          setInProcessPOs(parsed.filter((o: any) => o.status === 'In Process' || o.status === 'Partially Received'));
          setCompletedPOs(parsed.filter((o: any) => o.status === 'Completed / Received'));
          setHistoryPOs(parsed);
        } catch (e) { }
      }
    };
    loadSharedOrders();
    const handleStorage = () => loadSharedOrders();
    window.addEventListener('storage', handleStorage);
    window.addEventListener('orders-updated', handleStorage);
    return () => {
      window.removeEventListener('storage', handleStorage);
      window.removeEventListener('orders-updated', handleStorage);
    };
  }, []);

  const [showGrnModal, setShowGrnModal] = useState(false);
  const [selectedGrnPo, setSelectedGrnPo] = useState<any>(null);
  const [viewPoDetails, setViewPoDetails] = useState<any>(null);

  React.useEffect(() => {
    if (typeof window !== 'undefined') {
      try {
        if (Array.isArray(orders)) {
          const autoGen = localStorage.getItem('autoGeneratedProcurementRequests');
          let reqs = autoGen ? JSON.parse(autoGen) : [];
          if (!Array.isArray(reqs)) reqs = [];
          let updated = false;

          const targetKeywords = ['procurement', 'purchase requested', 'pending assignment'];

          orders.forEach((order: any) => {
            if (isStageMatch(order.stage, targetKeywords) ||
              isStageMatch(order.workflow_status, targetKeywords) ||
              isStageMatch(order.currentStage, targetKeywords) ||
              isStageMatch(order.workflowStage, targetKeywords)) {
              if (order.specs && Array.isArray(order.specs)) {
                order.specs.forEach((spec: any) => {
                  const available = spec.stockAvailable ?? 0;
                  if (spec.quantity > available) {
                    const shortageQty = spec.quantity - available;
                    const reqId = `PR-${order.poNumber}-${spec.id || 'SPEC'}`;
                    const exists = reqs.some((r: any) => r.id === reqId || (r.linkedPO === order.poNumber && r.material.includes(spec.itemDescription)));
                    if (!exists) {
                      const hsnCodes: Record<string, string> = {
                        "School Shirt": "620520",
                        "Corporate Shirt": "620530",
                        "School Pant": "620342",
                        "Denim Fabric": "520942",
                        "Cotton Fabric": "520811",
                        "Buttons": "960621",
                        "Thread": "520411",
                        "Hooks": "830810",
                        "Zippers": "960711",
                        "Labels": "580710"
                      };
                      let hsnCode = "620500";
                      for (const key in hsnCodes) {
                        if (spec.itemDescription.toLowerCase().includes(key.toLowerCase())) {
                          hsnCode = hsnCodes[key];
                          break;
                        }
                      }
                      reqs.push({
                        id: reqId,
                        material: `${spec.itemDescription} (HSN: ${hsnCode}) - ${spec.pattern}`,
                        category: 'Fabric',
                        required: spec.quantity,
                        available: available,
                        shortage: shortageQty,
                        unit: 'units',
                        supplier: 'Pending Assignment',
                        cost: shortageQty * (spec.unitPrice || 350),
                        priority: 'Critical',
                        status: 'Pending Procurement',
                        linkedPO: order.poNumber,
                        hsnCode,
                        description: `${spec.itemDescription} (${spec.size}) - ${spec.pattern}`
                      });
                      updated = true;
                    }
                  }
                });
              }
            } // Close isStageMatch if
          });

          if (updated) {
            localStorage.setItem('autoGeneratedProcurementRequests', JSON.stringify(reqs));
          }
        }
      } catch (e) {
        console.error("Error in automated out-of-stock routing:", e);
      }
    }

    const autoGen = localStorage.getItem('autoGeneratedProcurementRequests');
    let loadedRequests: any[] = [];
    if (autoGen) {
      try {
        const parsed = JSON.parse(autoGen);
        if (Array.isArray(parsed)) {
          loadedRequests = parsed;
        }
      } catch (e) { }
    }

    const archivedStr = localStorage.getItem('archivedProcurementRequests');
    if (archivedStr) {
      try { setArchivedRequests(JSON.parse(archivedStr)); } catch (e) { }
    }
  }, [orders]);

  React.useEffect(() => {
    if (typeof window !== 'undefined') {
      const params = new URLSearchParams(window.location.search);
      const currentPO = params.get('poNumber');
      if (currentPO) {
        setPoInput(currentPO);
      }

      const editSupplier = params.get('supplier');
      try {
        const session = localStorage.getItem('review_po_session');
        if (session) {
          const parsedSession = JSON.parse(session);

          const newOrderQuantities: Record<string, number | string> = {};
          const newSelectedSuppliers: Record<string, string> = {};
          const newArticleSplits: { id: string, parentId: string }[] = [];
          const allSuppliers = new Set<string>();

          const seenParents = new Set<string>();

          parsedSession.forEach((group: any) => {
            allSuppliers.add(group.supplierName);

            // In edit mode: only restore row state (orderQty / selected supplier / splits)
            // for the supplier being edited. Other suppliers' allocations are already
            // accounted for by the stagedQtyMap deduction on item.required, so loading
            // them here too causes totalAllocated to double-count and the dropdown to
            // have no selectable options.
            const shouldRestoreRows = !editSupplier || group.supplierName === editSupplier;

            if (shouldRestoreRows && group.items) {
              group.items.forEach((item: any) => {
                let targetId = item.id;

                if (seenParents.has(item.id)) {
                  targetId = `${item.id}-split-${Date.now()}-${Math.random().toString(36).substring(7)}`;
                  newArticleSplits.push({ id: targetId, parentId: item.id });
                } else {
                  seenParents.add(item.id);
                }

                newOrderQuantities[targetId] = item.orderQty;
                newSelectedSuppliers[targetId] = group.supplierName;
              });
            }
          });

          if (allSuppliers.size > 0) {
            // In edit mode: only filter to the edit supplier so the dropdown
            // shows just that vendor. Other suppliers' quantities are already
            // reflected via stagedQtyMap on item.required.
            setSupplierFilter(editSupplier ? [editSupplier] : Array.from(allSuppliers));
          }
          setOrderQuantities(prev => ({ ...prev, ...newOrderQuantities }));
          setSelectedSuppliers(prev => ({ ...prev, ...newSelectedSuppliers }));
          setArticleSplits(prev => [...prev, ...newArticleSplits]);
        }
      } catch (e) { }

      if (editSupplier) {
        setEditModeSupplier(editSupplier);
      }
    }
  }, []);

  useEffect(() => {
    const fetchSuppliers = async () => {
      try {
        console.log("Fetching suppliers from API...");
        const res = await fetch('http://127.0.0.1:5000/api/suppliers');
        
        if (!res.ok) {
          console.error(`Backend returned status ${res.status}`);
          setSuppliersList([]);
          setSuppliers([]);
          return;
        }

        const data = await res.json();
        console.log("RAW SUPPLIERS DATA FROM BACKEND:", data);

        let rawArray: any[] = [];
        // Safely extract array regardless of top-level key format
        if (Array.isArray(data)) {
          rawArray = data;
        } else if (data && Array.isArray(data.suppliers)) {
          rawArray = data.suppliers;
        } else if (data && Array.isArray(data.data)) {
          rawArray = data.data;
        } else {
          console.error("Unrecognized data format:", data);
          setSuppliersList([]);
          setSuppliers([]);
          return;
        }

        // Map to ensure 'name' exists for the lower table and other components
        const mappedData = rawArray.map((s: any) => ({
          ...s,
          name: s.name || s.supplier_name || s.company_name || 'Unnamed Supplier'
        }));

        setSuppliersList(mappedData);
        setSuppliers(mappedData);
      } catch (err) {
        console.error("Failed to connect to supplier endpoint:", err);
        setSuppliersList([]);
        setSuppliers([]);
      }
    };

    fetchSuppliers();
  }, []);
  const fetchStoreArticleShortages = async () => {
    try {
      const BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL || 'http://127.0.0.1:5000';
      const res = await fetch(`${BACKEND_URL}/procurement/dashboard`, {
        headers: {
          'Content-Type': 'application/json',
          'X-API-Key': 'sasons_read_only_key_2026_abc'
        }
      });
      const data = await res.json();
      if (data && Array.isArray(data.data)) {
        if (data.suppliers) {
          setSuppliersList(data.suppliers);
        }
        const activeData = data.data;
        return activeData
          .filter((item: any) => {
            const deficit = Number(item.deficit ?? 0);
            const status = String(item.status || '');
            const itemName = (item.article_name || item.name || '').toLowerCase();
            const hsn = item.hsn_code || '';

            if (itemName.includes('metal button') || hsn === '960621') {
              return false;
            }

            const hasShortage = deficit > 0 && status.toUpperCase() !== 'FULFILLED';
            return hasShortage;
          })
          .map((item: any) => {
            const available = Number(item.available_qty ?? 0);
            const minRequired = Number(item.min_required_qty ?? 0);
            const shortageQty = Number(item.deficit ?? 0);
            const materialName = item.article_name || 'Unknown Material';
            const hsn = item.hsn_code;
            const materialStr = hsn ? `${materialName} (HSN: ${hsn})` : materialName;

            const supplierMappingRaw = item.supplier_ids || item.available_suppliers || item.suppliers || item.preferred_supplier_ids || item.supplier_mapping || item.supplier_name || item.supplier || item.supplier_id;
            let supplierArray = [];

            if (Array.isArray(supplierMappingRaw)) {
              supplierArray = supplierMappingRaw.map(v => String(v));
            } else if (typeof supplierMappingRaw === 'string') {
              try {
                const parsed = JSON.parse(supplierMappingRaw);
                if (Array.isArray(parsed)) supplierArray = parsed.map(v => String(v));
                else supplierArray = [supplierMappingRaw];
              } catch {
                supplierArray = [supplierMappingRaw];
              }
            } else if (supplierMappingRaw != null) {
              supplierArray = [String(supplierMappingRaw)];
            } else {
              supplierArray = ['Store Restock'];
            }

            const supplierNames = supplierArray.map(supp => {
              const strSupp = String(supp).trim();
              const matchedSupplier = (data.suppliers || []).find((v: any) => String(v.id) === strSupp || String(v.name).toLowerCase() === strSupp.toLowerCase());
              return matchedSupplier ? matchedSupplier.name : strSupp;
            });

            return {
              id: `PR-STORE-${item.type}-${item.id}`,
              storeId: item.id,
              itemType: item.type === 'Garment' ? 'Stock Good' : 'Material',
              material: materialStr,
              category: item.category || 'General',
              required: minRequired,
              available: available,
              shortage: shortageQty,
              unit: item.unit || 'units',
              supplier: supplierNames[0] || 'Store Restock',
              allSuppliers: supplierNames,
              cost: shortageQty * (Number(item.unit_price) || 0),
              priority: available === 0 ? 'Critical' : 'High',
              status: 'Pending Procurement',
              linkedPO: null
            };
          });
      }
    } catch (err) {
      console.error('Failed to fetch store materials:', err);
    }
    return [];
  };

  React.useEffect(() => {
    let loadedRequests: any[] = [];
    const autoGen = localStorage.getItem('autoGeneratedProcurementRequests');
    if (autoGen) {
      try {
        const parsed = JSON.parse(autoGen);
        if (Array.isArray(parsed)) loadedRequests = parsed;
      } catch (e) { }
    }

    const fetchPOShortages = (selectedPoNumber: string) => {
      let related = loadedRequests.filter(p => p.linkedPO === selectedPoNumber);

      // Deduct already-staged quantities; only hide fully-allocated items
      try {
        const session = localStorage.getItem('review_po_session');
        if (session) {
          const parsedSession = JSON.parse(session);
          // Build a map of itemId -> total staged orderQty (across all suppliers)
          const stagedQtyMap = new Map<string, number>();
          parsedSession.forEach((group: any) => {
            if (group.supplierName !== editModeSupplier) {
              group.items.forEach((item: any) => {
                const originalId = (item.id || '').split('-split-')[0];
                stagedQtyMap.set(originalId, (stagedQtyMap.get(originalId) || 0) + (Number(item.orderQty) || 0));
              });
            }
          });
          related = related
            .map(req => {
              const staged = stagedQtyMap.get(req.id) || 0;
              if (staged <= 0) return req;
              const newRequired = Math.max(0, req.required - staged);
              return { ...req, required: newRequired, shortage: Math.max(0, newRequired - (req.available || 0)) };
            })
            .filter(req => req.required > 0); // hide only fully allocated
        }
      } catch (e) { }

      setMockShortages(related);

      const unrelated = loadedRequests.filter(p => p.linkedPO !== selectedPoNumber);
      if (unrelated.length > 0) {
        const archivedStr = localStorage.getItem('archivedProcurementRequests');
        const newArchived = unrelated.map(u => ({ ...u, archiveReason: 'Not Related To Current Order', archivedDate: new Date().toISOString() }));
        const allArchived = [...(archivedStr ? JSON.parse(archivedStr) : []), ...newArchived];
        localStorage.setItem('archivedProcurementRequests', JSON.stringify(allArchived));
        localStorage.setItem('autoGeneratedProcurementRequests', JSON.stringify(related));
        setArchivedRequests(allArchived);
      }
    };

    if (poInput === STORE_ARTICLES || !poInput || poInput.trim() === '') {
      // CALL STORE SHORTAGES FUNCTION
      fetchStoreArticleShortages().then(async (storeShortages) => {
        let localRequests: any[] = [];
        try {
          const res = await fetch('/api/procurement-requests?status=PENDING');
          if (res.ok) {
            const result = await res.json();
            if (result.success && result.data) {
              localRequests = result.data;
            }
          }
        } catch (e) {
          console.error("Failed to fetch API procurement requests", e);
        }

        const merged = [...storeShortages];
        localRequests.forEach(req => {
          if (!merged.find(m => m.id === req.id)) {
            merged.push({
              id: req.id,
              material: req.name + (req.sku ? ` (HSN: ${req.sku})` : ''),
              category: req.category || 'General',
              required: req.shortageQty || req.minRequired || 0,
              available: req.currentStock || 0,
              shortage: req.shortageQty || 0,
              unit: 'units',
              supplier: 'Store Restock',
              cost: 0,
              priority: 'High',
              status: req.status || 'Pending Procurement',
              linkedPO: null
            });
          }
        });

        let finalMerged = merged;
        // Deduct already-staged quantities; only hide fully-allocated items
        try {
          const session = localStorage.getItem('review_po_session');
          if (session) {
            const parsedSession = JSON.parse(session);
            // Build a map of itemId -> total staged orderQty (across all suppliers)
            const stagedQtyMap = new Map<string, number>();
            parsedSession.forEach((group: any) => {
              if (group.supplierName !== editModeSupplier) {
                group.items.forEach((item: any) => {
                  const originalId = (item.id || '').split('-split-')[0];
                  stagedQtyMap.set(originalId, (stagedQtyMap.get(originalId) || 0) + (Number(item.orderQty) || 0));
                });
              }
            });
            finalMerged = merged
              .map(req => {
                const staged = stagedQtyMap.get(req.id) || 0;
                if (staged <= 0) return req;
                const newShortage = Math.max(0, (req.shortage ?? req.required) - staged);
                return { ...req, shortage: newShortage, status: newShortage === 0 ? 'COMPLETED' : req.status };
              })
              .filter(req => (req.shortage ?? req.required) > 0 && req.status !== 'COMPLETED'); // hide only fully allocated
          }
        } catch (e) { }

        const strictlyFiltered = finalMerged.filter(req => (req.shortage ?? req.required) > 0 && String(req.status).toUpperCase() !== 'FULFILLED');

        setOrderQuantities(prev => {
          const updated = { ...prev };
          strictlyFiltered.forEach(item => {
            if (updated[item.id] === undefined) {
              updated[item.id] = 0;
            }
          });
          return updated;
        });
        setMockShortages(strictlyFiltered);
      });
    } else {
      // CALL REGULAR PO FUNCTION
      fetchPOShortages(poInput);
    }
  }, [poInput, editModeSupplier]);
  const activeRequests = React.useMemo(() => {
    return mockShortages.filter(item => {
      const isMetalButtons = String(item.material).toLowerCase().includes('metal button') || String(item.material).includes('960621');
      if (isMetalButtons) return false;

      const remaining = item.shortage ?? item.required ?? item.deficit ?? 0;
      const isFulfilled = String(item.status).toUpperCase() === 'FULFILLED' || String(item.status).toUpperCase() === 'COMPLETED' || item.isFulfilled === true;
      return remaining > 0 && !isFulfilled;
    });
  }, [mockShortages]);

  const totalShortages = activeRequests.length;
  const criticalItems = mockShortages.filter(i => i.available === 0).length;
  const estimatedCost = mockShortages.reduce((acc, curr) => acc + curr.cost, 0);

  const getPriorityStyle = (priority: string) => {
    switch (priority) {
      case 'Low': return 'bg-muted text-card-foreground border-border';
      case 'Medium': return 'bg-blue-100 text-blue-800 dark:text-blue-200 border-blue-200';
      case 'High': return 'bg-amber-100 text-amber-800 border-amber-200';
      case 'Critical': return 'bg-red-100 text-red-800 border-red-200';
      default: return 'bg-muted text-card-foreground border-border';
    }
  };

  const getStatusStyle = (status: string) => {
    switch (status) {
      case 'Pending Procurement': return 'bg-amber-100 text-amber-800 border-amber-200';
      case 'Supplier Assigned': return 'bg-blue-100 text-blue-800 dark:text-blue-200 border-blue-200';
      case 'Ordered': return 'bg-indigo-100 text-indigo-800 border-indigo-200';
      case 'Awaiting Delivery': return 'bg-purple-100 text-purple-800 border-purple-200';
      default: return 'bg-muted text-card-foreground border-border';
    }
  };



  const deduplicatedShortages = React.useMemo(() => {
    const grouped = new Map<string, any>();
    activeRequests.forEach(item => {
      const key = item.material; // Grouping by material name string (includes HSN)

      if (grouped.has(key)) {
        const existing = grouped.get(key);
        existing.required += item.required;
        existing.shortage += item.shortage;
        existing.cost += item.cost;

        if (!existing.originalIds) {
          existing.originalIds = [existing.id];
        }
        if (!existing.originalIds.includes(item.id)) {
          existing.originalIds.push(item.id);
        }
        existing.id = existing.originalIds.join(', ');
      } else {
        grouped.set(key, { ...item, originalIds: [item.id] });
      }
    });
    return Array.from(grouped.values());
  }, [activeRequests]);

  const filteredShortages = React.useMemo(() => {
    return Array.from(deduplicatedShortages.values()).filter(item => {
      const isMetalButtons = String(item.material).toLowerCase().includes('metal button') || String(item.material).includes('960621');
      if (isMetalButtons) return false;

      const matchesSearch = item.material.toLowerCase().includes(searchTerm.toLowerCase()) ||
        item.id.toLowerCase().includes(searchTerm.toLowerCase()) ||
        item.supplier.toLowerCase().includes(searchTerm.toLowerCase());
      const matchesStatus = statusFilter === 'All' || item.status === statusFilter;
      const matchesPriority = priorityFilter === 'All' || item.priority === priorityFilter;
      const matchesSupplier = supplierFilter.length === 0 || supplierFilter.some(filterStr => item.allSuppliers?.includes(filterStr));

      return matchesSearch && matchesStatus && matchesPriority && matchesSupplier;
    });
  }, [deduplicatedShortages, searchTerm, statusFilter, priorityFilter, supplierFilter]);

  const displayRows = React.useMemo(() => {
    const rows: any[] = [];
    filteredShortages.forEach(item => {
      rows.push({ ...item, rowId: item.id, isSplit: false });
      articleSplits.filter(s => s.parentId === item.id).forEach(split => {
        rows.push({ ...item, rowId: split.id, isSplit: true });
      });
    });
    return rows;
  }, [filteredShortages, articleSplits]);

  // Smart Auto-Selection Logic for Supplier Assignments
  React.useEffect(() => {
    if (supplierFilter.length === 1) {
      const singleSupplier = supplierFilter[0];
      setSelectedSuppliers(prev => {
        const next = { ...prev };
        let updated = false;
        displayRows.forEach(row => {
          if (next[row.rowId] !== singleSupplier) {
            next[row.rowId] = singleSupplier;
            updated = true;
          }
        });
        return updated ? next : prev;
      });
    } else if (supplierFilter.length === 0) {
      setSelectedSuppliers(prev => {
        if (Object.keys(prev).length === 0) return prev;
        return {};
      });
    } else {
      setSelectedSuppliers(prev => {
        const next = { ...prev };
        let updated = false;
        Object.keys(next).forEach(key => {
          if (next[key] && !supplierFilter.includes(next[key])) {
            delete next[key];
            updated = true;
          }
        });
        return updated ? next : prev;
      });
    }
  }, [supplierFilter, displayRows]);

  // Helper: build the current draft session groups from selections
  const buildDraftSessionGroups = React.useCallback(() => {
    const selectedItems = displayRows.filter(item => {
      const supplierName = selectedSuppliers[item.rowId] || (item.supplier !== 'Store Restock' && item.supplier !== 'Pending Assignment' ? item.supplier : null);
      const qty = Number(orderQuantities[item.rowId]) || 0;
      return supplierName && qty > 0;
    });

    const groupedBySupplier = new Map<string, any[]>();
    selectedItems.forEach(item => {
      const supplierName = selectedSuppliers[item.rowId] || item.supplier;
      const qty = Number(orderQuantities[item.rowId]) || 0;
      const unitPrice = item.cost ? (item.cost / (item.shortage || 1)) : 0;
      const cost = unitPrice * qty;

      if (!groupedBySupplier.has(supplierName)) {
        groupedBySupplier.set(supplierName, []);
      }
      const supplierItems = groupedBySupplier.get(supplierName)!;
      const existingItem = supplierItems.find(i => i.id === item.id);
      if (existingItem) {
        existingItem.orderQty += qty;
        existingItem.orderCost += cost;
      } else {
        supplierItems.push({ ...item, orderQty: qty, orderCost: cost });
      }
    });

    return Array.from(groupedBySupplier.entries()).map(([supplierName, items]) => {
      const supplierObj = suppliersList.find(s => s.name === supplierName) || null;
      return {
        supplierName,
        supplierObj,
        items
      };
    });
  }, [displayRows, orderQuantities, selectedSuppliers, suppliersList]);

  console.log("Suppliers array in component:", suppliers);

  return (
    <div className="max-w-7xl mx-auto space-y-4 sm:space-y-6 font-sans pb-8 relative">
      {viewPoDetails && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
          <div className="bg-card w-full max-w-2xl rounded-xl shadow-xl overflow-hidden flex flex-col">
            <div className="flex items-center justify-between px-6 py-4 border-b border-border bg-neutral-50/50 dark:bg-card/30">
              <div>
                <h3 className="text-lg font-bold text-foreground">Purchase Order Details</h3>
                <p className="text-sm text-muted-foreground">{viewPoDetails.id} • {viewPoDetails.supplier}</p>
              </div>
              <button
                onClick={() => setViewPoDetails(null)}
                className="text-neutral-400 hover:text-foreground transition-colors"
              >
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>

            <div className="p-6 space-y-6 overflow-y-auto max-h-[70vh]">
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <div className="p-3 bg-muted/30 rounded-lg border border-border">
                  <p className="text-xs text-muted-foreground uppercase tracking-wider mb-1">Delivered On</p>
                  <p className="text-sm font-semibold">{viewPoDetails.deliveredOn || 'N/A'}</p>
                </div>
                <div className="p-3 bg-muted/30 rounded-lg border border-border">
                  <p className="text-xs text-muted-foreground uppercase tracking-wider mb-1">Total Items</p>
                  <p className="text-sm font-semibold">{viewPoDetails.items}</p>
                </div>
                <div className="p-3 bg-muted/30 rounded-lg border border-border">
                  <p className="text-xs text-muted-foreground uppercase tracking-wider mb-1">Total Amount</p>
                  <p className="text-sm font-semibold text-indigo-600">₹{viewPoDetails.total?.toLocaleString()}</p>
                </div>
                <div className="p-3 bg-muted/30 rounded-lg border border-border">
                  <p className="text-xs text-muted-foreground uppercase tracking-wider mb-1">Status</p>
                  <p className="text-sm font-semibold text-emerald-600">Completed</p>
                </div>
              </div>
            </div>

            <div className="px-6 py-4 border-t border-border bg-neutral-50/50 dark:bg-card/30 flex justify-end">
              <button
                onClick={() => setViewPoDetails(null)}
                className="px-4 py-2 text-sm font-medium text-foreground bg-card border border-border rounded-lg shadow-sm hover:bg-muted transition-colors"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
      <ProcurementStepper dashboardCount={totalShortages} />

      {/* Edit Mode Banner */}
      {editModeSupplier && (
        <div className="bg-indigo-50 border border-indigo-200 dark:bg-indigo-900/20 dark:border-indigo-800 rounded-lg p-4 flex items-center justify-between shadow-sm">
          <div className="flex items-center gap-3">
            <div className="bg-indigo-100 p-2 rounded-full dark:bg-indigo-900/40">
              <Package className="w-5 h-5 text-indigo-700 dark:text-indigo-400" />
            </div>
            <div>
              <h3 className="text-sm font-semibold text-indigo-900 dark:text-indigo-300">
                Editing Purchase Order for {editModeSupplier}
              </h3>
              <p className="text-xs text-indigo-700/80 dark:text-indigo-400/80 mt-0.5">
                Save or Update Allocation when done.
              </p>
            </div>
          </div>
          <button
            onClick={() => {
              setEditModeSupplier(null);
              setSupplierFilter([]);
              window.history.replaceState({}, '', '/procurement');
            }}
            className="text-xs font-medium bg-white dark:bg-card px-3 py-1.5 rounded shadow-sm border border-indigo-100 dark:border-indigo-800 text-indigo-600 hover:bg-neutral-50 transition-colors"
          >
            Cancel Edit
          </button>
        </div>
      )}

      {/* Header Section */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-foreground flex items-center gap-2">
            <Truck className="h-6 w-6 text-indigo-600" />
            Procurement
          </h1>
          <p className="text-muted-foreground text-sm mt-1">{t('procurement.subtitle')}</p>
        </div>
        <div className="flex flex-col sm:flex-row gap-3 w-full sm:w-auto mt-4 sm:mt-0 items-center">

          <button
            onClick={() => router.push('/procurement/create-po')}
            className="w-full sm:w-auto px-4 py-2 bg-card border border-border text-neutral-700 dark:text-neutral-300 rounded-lg shadow-sm hover:bg-muted transition-colors font-medium text-sm flex items-center justify-center gap-2"
          >
            <Plus className="h-4 w-4" />
            {t('procurement.createRequest')}
          </button>
          <button
            onClick={() => router.push('/procurement/review-po')}
            className="w-full sm:w-auto px-4 py-2 bg-purple-50 text-purple-700 dark:bg-purple-900/30 dark:text-purple-300 border border-purple-200 dark:border-purple-800 rounded-lg shadow-sm hover:bg-purple-100 transition-colors font-medium text-sm flex items-center justify-center gap-2"
          >
            <ListChecks className="h-4 w-4" />
            View Purchase Orders
          </button>
          <button
            onClick={() => router.push('/procurement/suppliers')}
            className="w-full sm:w-auto px-4 py-2 bg-indigo-50 text-indigo-700 dark:bg-indigo-900/30 dark:text-indigo-300 border border-indigo-200 dark:border-indigo-800 rounded-lg shadow-sm hover:bg-indigo-100 transition-colors font-medium text-sm flex items-center justify-center gap-2"
          >
            <Building2 className="h-4 w-4" />
            Supplier Info
          </button>
          <button
            onClick={() => advanceStage('/procurement/review-po', 'Material Allocation')}
            className="w-full sm:w-auto px-4 py-2 bg-emerald-600 text-white rounded-lg shadow-sm hover:bg-emerald-700 transition-colors font-medium text-sm flex items-center justify-center gap-2"
          >
            <ListChecks className="h-4 w-4" />
            {t('procurement.continueAllocation')}
          </button>
        </div>
      </div>

      {/* Overview Cards */}
      {/* Overview Cards (Now Tabs) */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <div
          onClick={() => setActiveTab('pending')}
          className={`rounded-xl shadow-sm border p-4 sm:p-5 lg:p-6 flex items-center gap-4 cursor-pointer transition-all duration-200 ease-in-out hover:-translate-y-0.5 ${activeTab === 'pending' ? 'bg-card border-indigo-500 ring-1 ring-indigo-500' : 'bg-card border-border hover:border-indigo-400 hover:shadow-md'}`}
        >
          <div className="h-12 w-12 rounded-full flex items-center justify-center flex-shrink-0 bg-amber-100">
            <AlertTriangle className="h-6 w-6 text-amber-600" />
          </div>
          <div>
            <p className="text-sm font-semibold text-slate-700 dark:text-slate-200">Pending</p>
            <p className="text-2xl font-bold text-foreground">{totalShortages}</p>
          </div>
        </div>

        <div
          onClick={() => setActiveTab('in_process')}
          className={`rounded-xl shadow-sm border p-4 sm:p-5 lg:p-6 flex items-center gap-4 cursor-pointer transition-all duration-200 ease-in-out hover:-translate-y-0.5 ${activeTab === 'in_process' ? 'bg-card border-indigo-500 ring-1 ring-indigo-500' : 'bg-card border-border hover:border-indigo-400 hover:shadow-md'}`}
        >
          <div className="h-12 w-12 rounded-full flex items-center justify-center flex-shrink-0 bg-blue-100">
            <Truck className="h-6 w-6 text-blue-600" />
          </div>
          <div>
            <p className="text-sm font-semibold text-slate-700 dark:text-slate-200">In Process</p>
            <p className="text-2xl font-bold text-foreground">{inProcessPOs.length}</p>
          </div>
        </div>

        <div
          onClick={() => setActiveTab('completed')}
          className={`rounded-xl shadow-sm border p-4 sm:p-5 lg:p-6 flex items-center gap-4 cursor-pointer transition-all duration-200 ease-in-out hover:-translate-y-0.5 ${activeTab === 'completed' ? 'bg-card border-indigo-500 ring-1 ring-indigo-500' : 'bg-card border-border hover:border-indigo-400 hover:shadow-md'}`}
        >
          <div className="h-12 w-12 rounded-full flex items-center justify-center flex-shrink-0 bg-emerald-100">
            <CheckCircle2 className="h-6 w-6 text-emerald-600" />
          </div>
          <div>
            <p className="text-sm font-semibold text-slate-700 dark:text-slate-200">Completed / Received</p>
            <p className="text-2xl font-bold text-foreground">{completedPOs.length}</p>
          </div>
        </div>

        <div
          onClick={() => setActiveTab('history')}
          className={`rounded-xl shadow-sm border p-6 flex items-center gap-4 cursor-pointer transition-all duration-200 ease-in-out hover:-translate-y-0.5 ${activeTab === 'history' ? 'bg-card border-indigo-500 ring-1 ring-indigo-500' : 'bg-card border-border hover:border-indigo-400 hover:shadow-md'}`}
        >
          <div className="h-12 w-12 rounded-full flex items-center justify-center flex-shrink-0 bg-purple-100">
            <Clock className="h-6 w-6 text-purple-600" />
          </div>
          <div>
            <p className="text-sm font-semibold text-slate-700 dark:text-slate-200">Total Purchase History</p>
            <p className="text-lg font-bold text-foreground mt-1">{historyPOs.length} Orders</p>
          </div>
        </div>
      </div>

      {/* Procurement Requests Table */}
      {activeTab === 'pending' && (
        <div className="bg-card rounded-xl shadow-sm border border-border overflow-hidden">
          <div className="border-b border-border px-6 py-5">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
              <h2 className="text-lg font-semibold text-card-foreground">{t('procurement.requestsHeader')}</h2>

              <div className="flex flex-col sm:flex-row gap-4 items-center">
                {/* Search */}
                <div className="relative w-full sm:w-auto">
                  <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                    <Search className="h-4 w-4 text-neutral-400" />
                  </div>
                  <input
                    type="text"
                    placeholder="Search articles..."
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                    className="block w-full sm:w-64 pl-10 pr-3 py-2 border border-border rounded-lg focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm text-foreground bg-card"
                  />
                </div>

                {/* Multi-Select Supplier Filter */}
                <div className="relative w-full sm:w-auto">
                  <div
                    className="block w-full sm:w-56 pl-3 pr-10 py-2 border border-border rounded-lg bg-card cursor-pointer text-sm flex items-center justify-between"
                    onClick={() => setIsSupplierDropdownOpen(!isSupplierDropdownOpen)}
                  >
                    <span className="truncate text-foreground font-medium">
                      {supplierFilter.length === 0 ? 'All Suppliers' : `${supplierFilter.length} Supplier(s) Selected`}
                    </span>
                    <ChevronRight className={`h-4 w-4 text-neutral-400 transition-transform ${isSupplierDropdownOpen ? 'rotate-90' : ''}`} />
                  </div>

                  {isSupplierDropdownOpen && (
                    <div className="absolute right-0 mt-2 w-64 bg-[#0f172a] border border-slate-700 rounded-lg shadow-2xl z-50 p-2 flex flex-col gap-2">
                      
                      {/* Search Input */}
                      <input 
                        type="text" 
                        placeholder="Search suppliers..." 
                        value={supplierSearchTerm}
                        onChange={(e) => setSupplierSearchTerm(e.target.value)}
                        className="w-full bg-slate-900 border border-slate-700 rounded px-3 py-1.5 text-sm text-white focus:outline-none focus:border-blue-500"
                      />

                      {/* Explicit Scrollable Supplier List - THIS WAS MISSING */}
                      <div className="max-h-48 overflow-y-auto flex flex-col gap-1 pr-1">
                        <button
                          type="button"
                          onClick={() => {
                            setSelectedSupplierFilter(null);
                            setIsSupplierDropdownOpen(false);
                          }}
                          className="w-full text-left px-3 py-2 text-xs font-medium text-slate-300 hover:bg-slate-800 rounded transition-colors"
                        >
                          All Suppliers
                        </button>

                        {suppliersList && suppliersList.length > 0 ? (
                          suppliersList
                            .filter((s) => {
                              const sName = s.name || s.supplier_name || s.company_name || '';
                              return sName.toLowerCase().includes((supplierSearchTerm || '').toLowerCase());
                            })
                            .map((sup) => {
                              const displayName = sup.name || sup.supplier_name || sup.company_name || 'Unnamed';
                              return (
                                <button
                                  key={sup.id || displayName}
                                  type="button"
                                  onClick={() => {
                                    setSelectedSupplierFilter(sup);
                                    setIsSupplierDropdownOpen(false);
                                  }}
                                  className="w-full text-left px-3 py-2 text-xs text-white hover:bg-slate-800 rounded transition-colors flex items-center justify-between"
                                >
                                  <span>{displayName}</span>
                                </button>
                              );
                            })
                        ) : (
                          <div className="px-3 py-2 text-xs text-slate-400 italic">
                            {suppliersList ? 'No suppliers match search' : 'Loading suppliers...'}
                          </div>
                        )}
                      </div>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>

          <div className="overflow-x-auto w-full">
            <table className="w-full text-left border-collapse ">
              <thead>
                <tr className="bg-neutral-50 dark:bg-card border-b border-border text-[11px] uppercase tracking-wider text-muted-foreground font-medium">
                  <th className="px-4 py-3 text-left w-[24%]">Item Details</th>
                  <th className="px-4 py-3 text-center w-[14%]">Stock Status</th>
                  <th className="px-4 py-3 text-center w-[14%]">Deficit (Req Qty)</th>
                  <th className="px-4 py-3 text-center w-[24%]">Supplier</th>
                  <th className="px-4 py-3 text-center w-[14%]">Order Qty</th>
                  <th className="px-4 py-3 text-center w-[10%]">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-neutral-100 dark:divide-slate-800">
                {filteredShortages.length > 0 ? (
                  filteredShortages.map((item) => {
                    const splits = articleSplits.filter(s => s.parentId === item.id);
                    const totalRows = splits.length > 0 ? splits.length + 2 : 1;

                    const allRowIds = [item.id, ...splits.map(s => s.id)];

                    const getAvailableSuppliers = (currentRowId: string) => {
                      const selectedSupplierNames = allRowIds
                        .filter(id => id !== currentRowId)
                        .map(id => {
                          const val = selectedSuppliers[id];
                          if (val !== undefined) return val;
                          if (id === item.id) return (item.supplier === 'Store Restock' || item.supplier === 'Pending Assignment') ? '' : item.supplier;
                          return '';
                        })
                        .filter(Boolean);

                      return suppliersList.filter(
                        v => supplierFilter.includes(v.name) && !selectedSupplierNames.includes(v.name)
                      );
                    };

                    const isMaxSplitsReached = supplierFilter.length > 0 && getAvailableSuppliers('new-split-check').length === 0;

                    const totalAllocated = allRowIds.reduce((sum, id) => sum + (Number(orderQuantities[id]) || 0), 0);
                    const dynamicShortage = Math.max(0, (item.shortage ?? item.required) - totalAllocated);

                    return (
                      <React.Fragment key={item.id}>
                        <tr className={`hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors duration-150 ease-in-out ${editModeSupplier && Object.values(selectedSuppliers).includes(editModeSupplier) ? 'bg-indigo-50/20 dark:bg-indigo-900/10' : ''}`}>
                          <td className="px-4 py-3 align-top border-r border-border/50" rowSpan={totalRows}>
                            <div className="flex flex-col">
                              <span className={`text-sm font-medium ${dynamicShortage > 0 ? 'bg-red-50 text-red-700 px-2 py-1 rounded-lg inline-block font-semibold border border-red-100' : 'text-foreground'}`}>{item.material}</span>
                              <span className="text-xs text-muted-foreground mt-1">
                                {item.itemType ? (
                                  <span className={`inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider mr-2 ${item.itemType === 'Stock Good' || item.itemType === 'FINISHED GOODS' ? 'bg-purple-100 text-purple-700' : 'bg-blue-100 text-blue-700'}`}>
                                    {item.itemType === 'Stock Good' || item.itemType === 'STOCK_GOOD' || item.itemType === 'STOCK GOOD' ? 'FINISHED GOODS' : item.itemType === 'Material' || item.itemType === 'MATERIAL' ? 'ARTICLE' : item.itemType}
                                  </span>
                                ) : null}
                                {item.category} • {item.id.split(',')[0]}
                              </span>
                            </div>
                          </td>
                          <td className="px-4 py-3 text-center align-top border-r border-border/50" rowSpan={totalRows}>
                            <div className="flex flex-col items-center justify-center h-full">
                              <div className="text-sm font-semibold">{item.available} {item.unit}</div>
                              <div className="text-[10px] text-muted-foreground uppercase">Available</div>
                              <div className="w-8 border-b border-border my-1"></div>
                              <div className="text-sm font-medium">{item.required} {item.unit}</div>
                              <div className="text-[10px] text-muted-foreground uppercase">Min Required</div>
                            </div>
                          </td>
                          <td className="px-4 py-3 text-center align-top">
                            <div className="flex flex-col items-center justify-center h-full">
                              <span className={`text-sm font-bold ${totalAllocated > 0 ? (dynamicShortage === 0 ? 'text-emerald-600' : 'text-amber-600') : 'text-red-600'}`}>
                                {dynamicShortage}
                              </span>
                              {totalAllocated > 0 && dynamicShortage < item.shortage && (
                                <span className="text-xs text-muted-foreground line-through">{item.shortage}</span>
                              )}
                              <span className="text-xs text-muted-foreground">{item.unit === 'meters' ? (t('dashboard.stockAlerts.footer.metersRemaining') || 'meters') : item.unit === 'spools' ? (t('dashboard.stockAlerts.footer.spoolsRemaining') || 'spools') : (t('dashboard.stockAlerts.footer.unitsRemaining') || 'units')}</span>
                            </div>
                          </td>

                          <td className="px-4 py-3 align-top">
                            <select
                              className="block w-full py-1.5 pl-3 pr-8 border border-border rounded-lg sm:text-sm text-foreground appearance-none bg-card cursor-pointer"
                              value={selectedSuppliers[item.id] || (item.supplier === 'Store Restock' || item.supplier === 'Pending Assignment' ? '' : item.supplier)}
                              onChange={(e) => setSelectedSuppliers(prev => ({ ...prev, [item.id]: e.target.value }))}
                            >
                              {supplierFilter.length === 0 ? (
                                <option value="" disabled>Select Suppliers above first</option>
                              ) : (
                                <>
                                  <option value="" disabled>Select Supplier</option>
                                  {/* Always render the currently-selected option even if not in suppliersList */}
                                  {selectedSuppliers[item.id] && !getAvailableSuppliers(item.id).find(s => s.name === selectedSuppliers[item.id]) && (
                                    <option value={selectedSuppliers[item.id]}>{selectedSuppliers[item.id]}</option>
                                  )}
                                  {getAvailableSuppliers(item.id).map((supplier) => (
                                    <option key={supplier.id} value={supplier.name}>{supplier.name}</option>
                                  ))}
                                  {getAvailableSuppliers(item.id).length === 0 && !selectedSuppliers[item.id] && (
                                    <option value="" disabled>All selected suppliers allocated</option>
                                  )}
                                </>
                              )}
                            </select>
                          </td>

                          <td className="px-4 py-3 text-center align-top">
                            <div className="flex flex-col items-center justify-center gap-1">
                              <input
                                type="number"
                                min="0"
                                className="w-20 px-2 py-1 text-sm border border-border rounded focus:ring-indigo-500 focus:border-indigo-500 bg-card"
                                value={orderQuantities[item.id] !== undefined ? orderQuantities[item.id] : ''}
                                placeholder="0"
                                onChange={(e) => {
                                  const val = e.target.value;
                                  setOrderQuantities(prev => ({ ...prev, [item.id]: val === '' ? '' : parseFloat(val) }));
                                }}
                              />
                              {totalAllocated > 0 && (
                                <span className={`text-xs font-bold ${totalAllocated > item.required
                                  ? 'text-red-600'
                                  : dynamicShortage === 0
                                    ? 'text-emerald-600'
                                    : 'text-amber-600'
                                  }`}>
                                  {totalAllocated > item.required
                                    ? `Over by ${totalAllocated - item.required}`
                                    : dynamicShortage === 0
                                      ? 'Fulfilled ✓'
                                      : `Remaining: ${dynamicShortage}`}
                                </span>
                              )}
                            </div>
                          </td>

                          <td className="px-4 py-3 text-center align-top">
                            <div className="flex items-center justify-center gap-2">
                              <button
                                onClick={() => {
                                  if (isMaxSplitsReached) return;
                                  const newId = `${item.id}-split-${Date.now()}`;
                                  setArticleSplits(prev => [...prev, { id: newId, parentId: item.id }]);
                                  setOrderQuantities(prev => ({ ...prev, [newId]: 0 }));
                                }}
                                disabled={isMaxSplitsReached}
                                className={`p-1.5 rounded-md transition-colors ${isMaxSplitsReached ? 'text-neutral-300 cursor-not-allowed' : 'text-neutral-400 hover:text-indigo-600 hover:bg-indigo-50'}`}
                                title={isMaxSplitsReached ? "All selected suppliers allocated" : "Split Allocation"}
                              >
                                <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 7v8a2 2 0 002 2h6M8 7l-4 4m4-4l4 4m0 6l4-4m-4 4l-4-4" /></svg>
                              </button>
                            </div>
                          </td>
                        </tr>

                        {splits.map(split => (
                          <tr key={split.id} className="hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors duration-150 ease-in-out">
                            <td className="px-4 py-3 text-center text-sm text-muted-foreground align-top">-</td>

                            <td className="px-4 py-3 align-top">
                              <select
                                className="block w-full py-1.5 pl-3 pr-8 border border-border rounded-lg sm:text-sm text-foreground appearance-none bg-card cursor-pointer"
                                value={selectedSuppliers[split.id] || ''}
                                onChange={(e) => setSelectedSuppliers(prev => ({ ...prev, [split.id]: e.target.value }))}
                              >
                                {supplierFilter.length === 0 ? (
                                  <option value="" disabled>Select Suppliers above first</option>
                                ) : (
                                  <>
                                    <option value="" disabled>Select Supplier</option>
                                    {/* Always render the currently-selected option even if not in suppliersList */}
                                    {selectedSuppliers[split.id] && !getAvailableSuppliers(split.id).find(s => s.name === selectedSuppliers[split.id]) && (
                                      <option value={selectedSuppliers[split.id]}>{selectedSuppliers[split.id]}</option>
                                    )}
                                    {getAvailableSuppliers(split.id).map((supplier) => (
                                      <option key={supplier.id} value={supplier.name}>{supplier.name}</option>
                                    ))}
                                    {getAvailableSuppliers(split.id).length === 0 && !selectedSuppliers[split.id] && (
                                      <option value="" disabled>All selected suppliers allocated</option>
                                    )}
                                  </>
                                )}
                              </select>
                            </td>

                            <td className="px-4 py-3 text-center align-top">
                              <div className="flex flex-col items-center justify-center">
                                <input
                                  type="number"
                                  min="0"
                                  className="w-20 px-2 py-1 text-sm border border-border rounded focus:ring-indigo-500 focus:border-indigo-500 bg-card"
                                  value={orderQuantities[split.id] !== undefined ? orderQuantities[split.id] : ''}
                                  placeholder="0"
                                  onChange={(e) => {
                                    const val = e.target.value;
                                    setOrderQuantities(prev => ({ ...prev, [split.id]: val === '' ? '' : parseFloat(val) }));
                                  }}
                                />
                              </div>
                            </td>


                            <td className="px-4 py-3 text-center align-top">
                              <div className="flex items-center justify-center gap-2">
                                <button
                                  onClick={() => {
                                    setArticleSplits(prev => prev.filter(s => s.id !== split.id));
                                  }}
                                  className="p-1.5 text-neutral-400 hover:text-red-600 hover:bg-red-50 rounded-md transition-colors"
                                  title="Remove Split"
                                >
                                  <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" /></svg>
                                </button>
                              </div>
                            </td>
                          </tr>
                        ))}

                        {splits.length > 0 && (
                          <tr className="bg-indigo-50/50 dark:bg-indigo-900/10 font-medium">
                            <td className="px-4 py-2 border-t border-border"></td>
                            <td className="px-4 py-2 border-t border-border"></td>
                            <td className="px-4 py-2 text-right text-xs uppercase text-indigo-600/80 dark:text-indigo-400 border-t border-border">Total Combined Qty:</td>
                            <td className="px-4 py-2 text-center font-bold text-indigo-700 dark:text-indigo-300 border-t border-border">
                              {(Number(orderQuantities[item.id]) || 0) +
                                splits.reduce((sum, s) => sum + (Number(orderQuantities[s.id]) || 0), 0)}
                            </td>
                            <td colSpan={1} className="px-4 py-2 border-t border-border"></td>
                          </tr>
                        )}
                      </React.Fragment>
                    );
                  })
                ) : (
                  <tr>
                    <td colSpan={8} className="px-6 py-12 text-center text-muted-foreground">
                      <div className="flex flex-col items-center justify-center">
                        <Search className="h-8 w-8 text-neutral-300 mb-2" />
                        <p>
                          {supplierFilter.length > 0
                            ? 'No active shortages found for the selected supplier(s).'
                            : poInput === STORE_ARTICLES
                              ? 'No active material shortages found in Store.'
                              : (t('dashboard.recentOrders.headers.poNumber') || 'No procurement requests found.')}
                        </p>
                      </div>
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>

          <div className="bg-neutral-50 dark:bg-card px-4 py-3 border-t border-border flex items-center justify-between">
            <div className="flex items-center gap-4">
              <p className="text-sm text-muted-foreground">
                {t('inventoryVal.showing') || 'Showing'} <span className="font-medium text-foreground">1</span> {t('inventoryVal.to') || 'to'} <span className="font-medium text-foreground">{filteredShortages.length}</span> {t('inventoryVal.of') || 'of'} <span className="font-medium text-foreground">{totalShortages}</span>
              </p>
              <button
                onClick={() => {
                  const selectedItems = displayRows.filter(item => {
                    const supplierName = selectedSuppliers[item.rowId] || (item.supplier !== 'Store Restock' && item.supplier !== 'Pending Assignment' ? item.supplier : null);
                    const qty = Number(orderQuantities[item.rowId]) || 0;
                    return supplierName && qty > 0;
                  });

                  if (selectedItems.length === 0) {
                    alert("Please assign a supplier and ensure quantity is greater than 0 for at least one item to generate a Purchase Order.");
                    return;
                  }

                  // --- Deduct quantities from local state so the table updates live ---
                  const updatedMockShortages = mockShortages.map(req => {
                    const ordered = selectedItems.filter(i => {
                      if (i.originalIds) return i.originalIds.includes(req.id);
                      return i.id === req.id || i.id.startsWith(`${req.id}-split-`);
                    });
                    if (ordered.length > 0) {
                      const totalOrderedQty = ordered.reduce((sum, item) => sum + (Number(orderQuantities[item.rowId]) || 0), 0);
                      const currentAmount = req.shortage ?? req.required;
                      const newAmount = Math.max(0, currentAmount - totalOrderedQty);
                      return {
                        ...req,
                        shortage: newAmount,
                        status: newAmount === 0 ? 'COMPLETED' : 'IN_PROCESS'
                      };
                    }
                    return req;
                  });
                  // Filter out fully fulfilled items from the pending table
                  setMockShortages(updatedMockShortages.filter(r => r.status !== 'COMPLETED'));

                  // --- Persist deductions to localStorage (autoGeneratedProcurementRequests) ---
                  try {
                    const autoGenStr = localStorage.getItem('autoGeneratedProcurementRequests');
                    if (autoGenStr) {
                      const autoGen = JSON.parse(autoGenStr);
                      const updated = autoGen.map((req: any) => {
                        const ordered = selectedItems.filter(i => {
                          if (i.originalIds) return i.originalIds.includes(req.id);
                          return i.id === req.id || i.id.startsWith(`${req.id}-split-`);
                        });
                        if (ordered.length > 0) {
                          const totalOrderedQty = ordered.reduce((sum, item) => sum + (Number(orderQuantities[item.rowId]) || 0), 0);
                          const currentAmount = req.shortage ?? req.required;
                          const newAmount = Math.max(0, currentAmount - totalOrderedQty);
                          return {
                            ...req,
                            shortage: newAmount,
                            status: newAmount === 0 ? 'COMPLETED' : 'IN_PROCESS'
                          };
                        }
                        return req;
                      });
                      localStorage.setItem('autoGeneratedProcurementRequests', JSON.stringify(updated));
                    }
                  } catch (e) {
                    console.error("Failed to update autoGeneratedProcurementRequests", e);
                  }

                  // --- Persist deductions to localStorage (procurement_requests) ---
                  try {
                    const procReqStr = localStorage.getItem('procurement_requests');
                    if (procReqStr) {
                      const procReq = JSON.parse(procReqStr);
                      const updated = procReq.map((req: any) => {
                        const reqIdStr = `PR-STORE-${req.itemId}`;
                        const ordered = selectedItems.filter(i => {
                          if (i.originalIds) return i.originalIds.includes(req.id) || i.originalIds.includes(reqIdStr);
                          return i.id === req.id || i.id === reqIdStr || i.id.startsWith(`${req.id}-split-`) || i.id.startsWith(`${reqIdStr}-split-`);
                        });
                        if (ordered.length > 0) {
                          const totalOrderedQty = ordered.reduce((sum, item) => sum + (Number(orderQuantities[item.rowId]) || 0), 0);
                          const currentAmount = req.shortageQty ?? req.requiredQty ?? req.required;
                          const newAmount = Math.max(0, currentAmount - totalOrderedQty);
                          return {
                            ...req,
                            shortageQty: newAmount,
                            status: newAmount === 0 ? 'COMPLETED' : 'IN_PROCESS'
                          };
                        }
                        return req;
                      });
                      localStorage.setItem('procurement_requests', JSON.stringify(updated));
                    }
                  } catch (e) {
                    console.error("Failed to update procurement_requests", e);
                  }

                  // --- Build & PERSIST draft PO session to localStorage NOW (only on explicit click) ---
                  const newGroups = buildDraftSessionGroups();
                  let existingSession: any[] = [];
                  try {
                    const session = localStorage.getItem('review_po_session');
                    if (session) existingSession = JSON.parse(session);
                  } catch (e) { }
                  // Only overwrite suppliers currently being allocated
                  const suppliersBeingManaged = new Set(supplierFilter);
                  existingSession = existingSession.filter((g: any) => !suppliersBeingManaged.has(g.supplierName));
                  newGroups.forEach(newGroup => existingSession.push(newGroup));
                  localStorage.setItem('review_po_session', JSON.stringify(existingSession));
                  window.dispatchEvent(new Event('storage'));

                  router.push('/procurement/review-po');
                }}
                className="px-4 py-2 bg-indigo-600 text-white rounded-md text-sm font-medium hover:bg-indigo-700 transition-colors flex items-center gap-2 shadow-sm disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <Plus className="h-4 w-4" />
                Create Purchase Orders
              </button>
            </div>
            <div className="flex items-center gap-2">
              <button className="p-2 border border-border rounded-md bg-card text-neutral-400 hover:text-neutral-700 hover:bg-muted disabled:opacity-50 disabled:cursor-not-allowed transition-colors" disabled>
                <ChevronLeft className="h-4 w-4" />
              </button>
              <button className="p-2 border border-border rounded-md bg-card text-neutral-400 hover:text-neutral-700 hover:bg-muted transition-colors">
                <ChevronRight className="h-4 w-4" />
              </button>
            </div>
          </div>
        </div>
      )}

      {/* In Process Tab */}
      {activeTab === 'in_process' && (
        <div className="bg-card rounded-xl shadow-sm border border-border overflow-hidden">
          <div className="border-b border-border px-6 py-5">
            <h2 className="text-lg font-semibold text-card-foreground">Active Purchase Orders</h2>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse whitespace-nowrap">
              <thead>
                <tr className="bg-muted/50 border-y border-border text-xs uppercase tracking-wider text-muted-foreground font-semibold">
                  <th className="px-6 py-4">PO Number</th>
                  <th className="px-6 py-4">Supplier</th>
                  <th className="px-6 py-4">Order Date</th>
                  <th className="px-6 py-4">Est. Delivery</th>
                  <th className="px-6 py-4">Total Amount</th>
                  <th className="px-6 py-4">Status</th>
                  <th className="px-6 py-4 text-center">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {inProcessPOs.map((po) => (
                  <tr key={po.id} className="hover:bg-muted/30 transition-colors">
                    <td className="px-6 py-4 font-medium">{po.id}</td>
                    <td className="px-6 py-4">{po.supplier}</td>
                    <td className="px-6 py-4">{po.date}</td>
                    <td className="px-6 py-4">{po.expectedDelivery}</td>
                    <td className="px-6 py-4">₹{po.total.toLocaleString()}</td>
                    <td className="px-6 py-4">
                      <span className={`inline-flex items-center px-2 py-1 rounded text-xs font-medium border ${po.status === 'Partially Received' ? 'bg-amber-50 text-amber-700 border-amber-200' : 'bg-blue-50 text-blue-700 border-blue-200'}`}>
                        {po.status}
                      </span>
                    </td>
                    <td className="px-6 py-4 flex items-center justify-center gap-2">
                      <button className="p-1.5 text-neutral-500 hover:text-indigo-600 hover:bg-indigo-50 rounded transition-colors" title="Export PDF">
                        <Download className="h-4 w-4" />
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Completed Tab */}
      {activeTab === 'completed' && (
        <div className="bg-card rounded-xl shadow-sm border border-border overflow-hidden">
          <div className="border-b border-border px-6 py-5">
            <h2 className="text-lg font-semibold text-card-foreground">Awaiting Goods Receipt Note (GRN)</h2>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse whitespace-nowrap">
              <thead>
                <tr className="bg-muted/50 border-y border-border text-xs uppercase tracking-wider text-muted-foreground font-semibold">
                  <th className="px-6 py-4">PO Number</th>
                  <th className="px-6 py-4">GRN Number</th>
                  <th className="px-6 py-4">Supplier</th>
                  <th className="px-6 py-4">Receiving Date</th>
                  <th className="px-6 py-4">Quantity Received</th>
                  <th className="px-6 py-4">Status</th>
                  <th className="px-6 py-4 text-center">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {completedPOs.map((po) => (
                  <tr key={po.id} className="hover:bg-muted/30 transition-colors">
                    <td className="px-6 py-4 font-medium">{po.id}</td>
                    <td className="px-6 py-4 text-xs font-mono">{po.grnNumbers?.join(', ') || 'N/A'}</td>
                    <td className="px-6 py-4">{po.supplier}</td>
                    <td className="px-6 py-4">{po.receivingDates?.join(', ') || po.deliveredOn || 'N/A'}</td>
                    <td className="px-6 py-4 font-medium">{po.receivedQty} / {po.items}</td>
                    <td className="px-6 py-4">
                      <span className={`inline-flex items-center px-2 py-1 rounded text-xs font-medium bg-emerald-50 text-emerald-700 border-emerald-200`}>
                        {po.status}
                      </span>
                    </td>
                    <td className="px-6 py-4 flex items-center justify-center gap-2">
                      <button onClick={() => generateProcurementPDF(po)} className="p-1.5 text-neutral-500 hover:text-indigo-600 hover:bg-indigo-50 rounded transition-colors" title="Download PDF">
                        <Download className="h-4 w-4" />
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* History Tab */}
      {activeTab === 'history' && (
        <div className="bg-card rounded-xl shadow-sm border border-border overflow-hidden">
          <div className="border-b border-border px-6 py-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <h2 className="text-lg font-semibold text-card-foreground">Purchase History Archive</h2>
            <div className="flex flex-col sm:flex-row gap-2">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-neutral-400" />
                <input type="text" placeholder="Search PO or Supplier..." className="pl-9 pr-3 py-1.5 rounded-lg border border-border text-sm w-full sm:w-48 bg-card" />
              </div>
              <input type="date" className="px-3 py-1.5 rounded-lg border border-border text-sm bg-card" />
            </div>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse whitespace-nowrap">
              <thead>
                <tr className="bg-muted/50 border-y border-border text-xs uppercase tracking-wider text-muted-foreground font-semibold">
                  <th className="px-6 py-4">PO Number</th>
                  <th className="px-6 py-4">Supplier</th>
                  <th className="px-6 py-4">Delivered On</th>
                  <th className="px-6 py-4">Items</th>
                  <th className="px-6 py-4">Total Amount</th>
                  <th className="px-6 py-4 text-center">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {historyPOs.map((po) => (
                  <tr key={po.id} className="hover:bg-muted/30 transition-colors">
                    <td className="px-6 py-4 font-medium">{po.id}</td>
                    <td className="px-6 py-4">{po.supplier}</td>
                    <td className="px-6 py-4">{po.deliveredOn}</td>
                    <td className="px-6 py-4">{po.items}</td>
                    <td className="px-6 py-4">₹{po.total.toLocaleString()}</td>
                    <td className="px-6 py-4 flex items-center justify-center gap-2">
                      <button
                        className="p-1.5 text-neutral-500 hover:text-indigo-600 hover:bg-indigo-50 rounded transition-colors"
                        title="View Details"
                        onClick={() => setViewPoDetails(po)}
                      >
                        <Eye className="h-4 w-4" />
                      </button>
                      <button className="p-1.5 text-neutral-500 hover:text-indigo-600 hover:bg-indigo-50 rounded transition-colors" title="Export PDF">
                        <Download className="h-4 w-4" />
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Lower Section: Grid layout for Suppliers & Timeline */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">

        {/* Supplier Summary */}
        <div className="lg:col-span-2 bg-card rounded-xl shadow-sm border border-border overflow-hidden">
          <div className="border-b border-border px-6 py-5 bg-neutral-50/50 dark:bg-card/30">
            <h2 className="text-lg font-semibold text-card-foreground flex items-center gap-2">
              <Building2 className="h-5 w-5 text-muted-foreground" />
              {t('procurement.supplierSummary') || 'Supplier Directory Summary'}
            </h2>
          </div>
          <div className="w-full">
            <table className="w-full text-left border-collapse table-fixed">
              <thead>
                <tr className="bg-card border-b border-neutral-100 dark:border-border text-[11px] uppercase tracking-wider text-muted-foreground font-medium">
                  <th className="px-2 py-3 w-[22%] break-words">{t('bom.customer') || 'Supplier Name'}</th>
                  <th className="px-2 py-3 w-[25%] break-words">{t('inventoryVal.materialsHeader') || 'Materials Supplied'}</th>
                  <th className="px-2 py-3 w-[15%] break-words">{t('leadTime') || 'Lead Time'}</th>
                  <th className="px-2 py-3 w-[18%] break-words">{t('performance') || 'Rating'}</th>
                  <th className="px-2 py-3 w-[20%] break-words">{t('dashboard.recentOrders.headers.status') || 'Status & Contact'}</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-neutral-100 dark:divide-slate-800">
                {suppliers.length > 0 ? (
                  suppliers.map((supplier, idx) => (
                    <tr key={idx} className="hover:bg-neutral-50/50 dark:hover:bg-slate-800/30 transition-colors">
                      <td className="px-2 py-3 break-words">
                        <div className="flex flex-col">
                          <span className="text-sm font-medium text-foreground flex items-center gap-1 flex-wrap">
                            {supplier.name}
                            {supplier.preferred && <span title={t('procurement.preferredSupplier') || 'Preferred Supplier'}><Star className="h-3 w-3 text-amber-500 fill-amber-500 shrink-0" /></span>}
                          </span>
                        </div>
                      </td>
                      <td className="px-2 py-3 text-[13px] text-muted-foreground break-words">{supplier.materials}</td>
                      <td className="px-2 py-3 text-[13px] text-muted-foreground break-words">{supplier.leadTime}</td>
                      <td className="px-2 py-3">
                        <div className="flex flex-col xl:flex-row items-start xl:items-center gap-2">
                          <div className="w-full max-w-[40px] xl:max-w-[60px] bg-muted rounded-full h-1.5 overflow-hidden">
                            <div
                              className={`h-1.5 rounded-full ${supplier.performance >= 95 ? 'bg-emerald-500' : supplier.performance >= 90 ? 'bg-amber-500' : 'bg-red-500'}`}
                              style={{ width: `${supplier.performance}%` }}
                            />
                          </div>
                          <span className="text-xs font-medium text-neutral-700 dark:text-neutral-300">{supplier.performance}%</span>
                        </div>
                      </td>
                      <td className="px-2 py-3">
                        <div className="flex flex-col xl:flex-row items-start xl:items-center justify-between gap-2 text-sm">
                          <span className={`inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider whitespace-normal text-center ${supplier.status === 'Active' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>
                            {supplier.status === 'Active' ? (t('dashboard.stockAlerts.severity.low') || 'Active') : (t('dashboard.stockAlerts.severity.low') || 'Under Review')}
                          </span>
                          <div className="flex gap-1.5 text-neutral-400 mt-1 xl:mt-0">
                            <button className="hover:text-blue-600 transition-colors" title={`Email ${supplier.contact}`}><Mail className="h-3.5 w-3.5" /></button>
                            <button className="hover:text-blue-600 transition-colors" title="Call Supplier"><Phone className="h-3.5 w-3.5" /></button>
                          </div>
                        </div>
                      </td>
                    </tr>
                  ))
                ) : (
                  <tr>
                    <td colSpan={5} className="px-6 py-12 text-center text-muted-foreground">
                      <div className="flex flex-col items-center justify-center">
                        <Building2 className="h-8 w-8 text-neutral-300 mb-2" />
                        <p>No suppliers linked to selected materials.</p>
                      </div>
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>

        {/* Workflow Progression */}
        <div className="lg:col-span-1 bg-gradient-to-br from-indigo-50 to-blue-50 dark:from-indigo-950/40 dark:to-blue-900/30 rounded-xl shadow-sm border border-indigo-100 dark:border-indigo-800/50 overflow-hidden flex flex-col">
          <div className="border-b border-indigo-100 dark:border-indigo-800/50 px-6 py-5 bg-white/50 dark:bg-card/50 backdrop-blur-sm">
            <h2 className="text-lg font-semibold text-indigo-900 dark:text-indigo-100 flex items-center gap-2">
              <CheckCircle2 className="h-5 w-5 text-indigo-600 dark:text-indigo-400" />
              {t('procurement.procCompletion') || 'Procurement Completion'}
            </h2>
            <p className="text-xs text-indigo-600/80 dark:text-indigo-400/80 mt-1">{t('procurement.nextSteps') || 'Next steps after shortage resolution'}</p>
          </div>
          <div className="p-6 flex-1 flex flex-col justify-between">
            <div className="space-y-4 relative before:absolute before:inset-0 before:ml-2.5 before:-translate-x-px before:h-full before:w-0.5 before:bg-indigo-200">
              <div className="relative flex items-center group">
                <div className="flex items-center justify-center w-5 h-5 rounded-full border-2 bg-card flex-shrink-0 z-10 border-indigo-600 text-indigo-600">
                  <div className="w-2 h-2 bg-indigo-600 rounded-full" />
                </div>
                <div className="ml-4">
                  <span className="text-sm font-semibold text-foreground">{t('orderInitiation.tracker.procurement') || 'Procurement'}</span>
                  <p className="text-xs text-muted-foreground">{t('procurement.shortageItems') || 'Shortage resolution'}</p>
                </div>
              </div>
              <div className="relative flex items-center group">
                <div className="flex items-center justify-center w-5 h-5 rounded-full border-2 bg-card flex-shrink-0 z-10 border-indigo-400 text-indigo-400" />
                <div className="ml-4">
                  <span className="text-sm font-semibold text-muted-foreground">{t('orderInitiation.tracker.materialAllocation') || 'Material Allocation'}</span>
                  <p className="text-xs text-neutral-400">{t('Allocate Warehouse') || 'Allocate from warehouse'}</p>
                </div>
              </div>
              <div className="relative flex items-center group">
                <div className="flex items-center justify-center w-5 h-5 rounded-full border-2 bg-card flex-shrink-0 z-10 border-border text-transparent" />
                <div className="ml-4">
                  <span className="text-sm font-semibold text-neutral-400">{t('Freeze Materials') || 'Freeze Materials'}</span>
                  <p className="text-xs text-neutral-400">{t('Lock Stock') || 'Lock stock for PO'}</p>
                </div>
              </div>
              <div className="relative flex items-center group">
                <div className="flex items-center justify-center w-5 h-5 rounded-full border-2 bg-card flex-shrink-0 z-10 border-border text-transparent" />
                <div className="ml-4">
                  <span className="text-sm font-semibold text-neutral-400">{t('orderInitiation.tracker.production') || 'Production'}</span>
                  <p className="text-xs text-neutral-400">{t('Begin Manufacturing') || 'Begin manufacturing'}</p>
                </div>
              </div>
            </div>

            <button
              onClick={() => advanceStage('/procurement/review-po', 'Material Allocation')}
              className="mt-8 w-full px-4 py-3 bg-indigo-600 text-white rounded-lg shadow-md hover:bg-indigo-700 transition-colors font-medium text-sm flex items-center justify-center gap-2 group"
            >
              {t('procurement.continueAllocation')}
              <ArrowRight className="h-4 w-4 group-hover:translate-x-1 transition-transform" />
            </button>
            <button
              onClick={() => router.push('/procurement/create-po')}
              className="mt-3 w-full px-4 py-3 bg-card border border-border text-neutral-700 dark:text-neutral-300 rounded-lg shadow-sm hover:bg-muted transition-colors font-medium text-sm flex items-center justify-center gap-2"
            >
              <Plus className="h-4 w-4" />
              {t('procurement.createRequest')}
            </button>
          </div>
        </div>
      </div>

      {/* Archive Box */}
      {archivedRequests.length > 0 && (
        <div className="bg-card rounded-xl shadow-sm border border-border overflow-hidden mt-8">
          <div className="border-b border-border px-6 py-5 bg-neutral-50/50 dark:bg-card/30">
            <h2 className="text-lg font-semibold text-card-foreground">Archive Box</h2>
          </div>
          <div className="overflow-x-auto w-full">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-neutral-50 dark:bg-card/50 border-b border-border text-[11px] uppercase tracking-wider text-muted-foreground font-medium">
                  <th className="px-6 py-3">Material Name</th>
                  <th className="px-4 py-3">PO Number</th>
                  <th className="px-4 py-3">Archived Date</th>
                  <th className="px-4 py-3">Reason</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-neutral-100 dark:divide-slate-800">
                {archivedRequests.map((item, idx) => (
                  <tr key={idx} className="hover:bg-neutral-50/80 transition-colors">
                    <td className="px-6 py-3 text-sm font-medium text-foreground">{item.material}</td>
                    <td className="px-4 py-3 text-sm text-muted-foreground">{item.linkedPO}</td>
                    <td className="px-4 py-3 text-sm text-muted-foreground">{formatDateDisplay(item.archivedDate)}</td>
                    <td className="px-4 py-3 text-sm text-neutral-500 italic">{item.archiveReason}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
      {/* GRN Upload Modal */}
      {showGrnModal && selectedGrnPo && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
          <div className="bg-card rounded-xl shadow-xl w-full max-w-md overflow-hidden">
            <div className="px-6 py-4 border-b border-border flex justify-between items-center">
              <h3 className="text-lg font-semibold text-foreground">Upload Goods Receipt Note</h3>
              <button onClick={() => setShowGrnModal(false)} className="text-muted-foreground hover:text-foreground text-xl leading-none">&times;</button>
            </div>
            <div className="p-6 space-y-4">
              <div>
                <p className="text-sm font-medium text-foreground mb-1">Purchase Order</p>
                <p className="text-sm text-muted-foreground">{selectedGrnPo.id} ({selectedGrnPo.supplier})</p>
              </div>
              <div className="border-2 border-dashed border-border rounded-lg p-8 flex flex-col items-center justify-center gap-3">
                <FileUp className="h-8 w-8 text-neutral-400" />
                <p className="text-sm text-center text-muted-foreground">Drag and drop your GRN document here, or click to browse</p>
                <input type="file" className="hidden" id="grn-upload" />
                <label htmlFor="grn-upload" className="px-4 py-2 bg-neutral-100 dark:bg-neutral-800 text-sm font-medium rounded-md cursor-pointer hover:bg-neutral-200 dark:hover:bg-neutral-700 transition-colors">
                  Select File
                </label>
              </div>
            </div>
            <div className="px-6 py-4 bg-muted/30 border-t border-border flex justify-end gap-3">
              <button
                onClick={() => setShowGrnModal(false)}
                className="px-4 py-2 bg-transparent text-foreground border border-border rounded-lg text-sm font-medium hover:bg-muted transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={() => {
                  setCompletedPOs(prev => prev.map(po =>
                    po.id === selectedGrnPo.id ? { ...po, status: 'Received & Completed' } : po
                  ));
                  setShowGrnModal(false);
                  alert("GRN Uploaded Successfully!");
                }}
                className="px-4 py-2 bg-emerald-600 text-white rounded-lg text-sm font-medium hover:bg-emerald-700 transition-colors flex items-center gap-2"
              >
                <CheckCircle2 className="h-4 w-4" />
                Submit GRN
              </button>
            </div>
          </div>
        </div>
      )}


    </div>
  );
}