"use client";

import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowLeft, CheckCircle2, Package, Truck, Building2, ExternalLink, ChevronDown, ChevronUp } from 'lucide-react';
import ProcurementStepper from '@/components/ProcurementStepper';

interface ReviewItem {
  id: string;
  material: string;
  shortage: number;
  cost: number;
  unit: string;
  orderQty: number;
  orderCost: number;
}

interface SupplierGroup {
  supplierName: string;
  items: ReviewItem[];
}

export default function ReviewPurchaseOrdersPage() {
  const router = useRouter();

  const [sessionData, setSessionData] = useState<SupplierGroup[]>([]);
  const [supplierStatus, setSupplierStatus] = useState<Record<string, { status: 'pending' | 'success', poNumber?: string }>>({});

  const [branch, setBranch] = useState('Main Plant');
  const [transportMode, setTransportMode] = useState('Road Transport');
  const [expandedMap, setExpandedMap] = useState<Record<string, boolean>>({});

  useEffect(() => {
    const loadSession = () => {
      const data = localStorage.getItem('review_po_session');
      if (data) {
        try {
          const parsed: SupplierGroup[] = JSON.parse(data);
          setSessionData(parsed);
          setSupplierStatus(prev => {
            const newStatus = { ...prev };
            parsed.forEach(group => {
              if (!newStatus[group.supplierName]) {
                newStatus[group.supplierName] = { status: 'pending' };
              }
            });
            return newStatus;
          });
        } catch (e) {
          console.error("Failed to parse review_po_session", e);
        }
      }
    };

    loadSession();
    window.addEventListener('storage', loadSession);
    return () => window.removeEventListener('storage', loadSession);
  }, []);

  const processCreatePO = (group: SupplierGroup, poNumber: string) => {
    // 1. Generate Official PO Record in sharedPurchaseOrders
    const sharedOrdersStr = localStorage.getItem('sharedPurchaseOrders');
    let sharedOrders = sharedOrdersStr ? JSON.parse(sharedOrdersStr) : [];

    const totalCost = group.items.reduce((sum, item) => sum + item.orderCost, 0);
    const materials = group.items.map(item => ({
      itemDescription: item.material,
      quantity: item.orderQty,
      unitPrice: item.orderCost / (item.orderQty || 1),
      amount: item.orderCost
    }));

    sharedOrders.push({
      id: poNumber,
      supplier: group.supplierName,
      supplierAddress: 'Address on file',
      items: group.items.length,
      total: totalCost,
      date: new Date().toISOString().split('T')[0],
      status: "In Process",
      expectedDelivery: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      receivedQty: 0,
      grnNumbers: [],
      receivingDates: [],
      details: materials
    });
    localStorage.setItem('sharedPurchaseOrders', JSON.stringify(sharedOrders));

    // 2. Clean Up Procurement Requests (Deduct Required Qty & Shortage) via API
    const autoGenStr = localStorage.getItem('autoGeneratedProcurementRequests');
    if (autoGenStr) {
      let autoGenReqs: any[] = JSON.parse(autoGenStr);

      // Update local storage for UI consistency and sync with backend
      group.items.forEach(orderedItem => {
        const originalId = orderedItem.id.split('-split-')[0];
        const reqIndex = autoGenReqs.findIndex(req => req.id === originalId);

        if (reqIndex !== -1) {
          const newRequired = Math.max(autoGenReqs[reqIndex].required - orderedItem.orderQty, 0);
          const newShortage = Math.max(autoGenReqs[reqIndex].shortage - orderedItem.orderQty, 0);

          // Sync with backend
          fetch(`/api/procurement-requests/${originalId}`, {
            method: 'PATCH',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              required: newRequired,
              shortage_qty: newShortage,
              ...(newRequired === 0 ? { status: 'FULFILLED' } : {})
            })
          }).catch(console.error);

          // Update local copy
          autoGenReqs[reqIndex].required = newRequired;
          autoGenReqs[reqIndex].shortage = newShortage;

          if (newRequired === 0) {
            autoGenReqs.splice(reqIndex, 1);
          }
        }
      });
      localStorage.setItem('autoGeneratedProcurementRequests', JSON.stringify(autoGenReqs));
    }

    // 3. Remove from review_po_session draft
    const sessionStr = localStorage.getItem('review_po_session');
    if (sessionStr) {
      let existingSession: any[] = JSON.parse(sessionStr);
      existingSession = existingSession.filter(g => g.supplierName !== group.supplierName);
      localStorage.setItem('review_po_session', JSON.stringify(existingSession));
    }
  };

  const handleCreatePO = (supplierName: string) => {
    const group = sessionData.find(g => g.supplierName === supplierName);
    if (!group) return;

    const fakePoNumber = `PO-${supplierName.substring(0, 3).toUpperCase()}-${Date.now().toString().slice(-4)}`;

    processCreatePO(group, fakePoNumber);

    setSupplierStatus(prev => ({
      ...prev,
      [supplierName]: { status: 'success', poNumber: fakePoNumber }
    }));

    window.dispatchEvent(new Event('storage'));
    window.dispatchEvent(new Event('orders-updated'));
  };

  const handleCreateAll = () => {
    const newStatus = { ...supplierStatus };
    let anyCreated = false;

    sessionData.forEach(group => {
      if (newStatus[group.supplierName]?.status === 'pending') {
        const fakePoNumber = `PO-${group.supplierName.substring(0, 3).toUpperCase()}-${Date.now().toString().slice(-4)}`;
        processCreatePO(group, fakePoNumber);
        newStatus[group.supplierName] = { status: 'success', poNumber: fakePoNumber };
        anyCreated = true;
      }
    });

    if (anyCreated) {
      setSupplierStatus(newStatus);
      window.dispatchEvent(new Event('storage'));
      window.dispatchEvent(new Event('orders-updated'));
    }
  };

  const allSuccess = sessionData.length > 0 && sessionData.every(group => supplierStatus[group.supplierName]?.status === 'success');

  return (
    <div className="max-w-[1200px] mx-auto space-y-4 sm:space-y-6 font-sans pb-12 pt-6">
      <ProcurementStepper />

      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 border-b border-border pb-4">
        <div>
          <button
            onClick={() => router.push('/procurement')}
            className="flex items-center text-sm text-muted-foreground hover:text-foreground mb-2 transition-colors"
          >
            <ArrowLeft className="w-4 h-4 mr-1" />
            Back to Procurement Requests
          </button>
          <h1 className="text-2xl font-bold text-foreground">Review Purchase Orders</h1>
          <p className="text-sm text-muted-foreground mt-1">
            Batch process your pending purchase orders across {sessionData.length} suppliers.
          </p>
        </div>

        {sessionData.length > 0 && (
          <div className="flex items-center gap-3">
            <button
              onClick={() => {
                const allCurrentlyExpanded = sessionData.length > 0 && sessionData.every(g => expandedMap[g.supplierName] === true);
                const newMap: Record<string, boolean> = {};
                sessionData.forEach(g => { newMap[g.supplierName] = !allCurrentlyExpanded; });
                setExpandedMap(newMap);
              }}
              className="px-6 py-2.5 bg-card border border-border text-foreground font-medium rounded-lg shadow-sm hover:bg-muted transition-colors whitespace-nowrap"
            >
              {sessionData.length > 0 && sessionData.every(g => expandedMap[g.supplierName] === true) ? 'Collapse All' : 'Expand All'}
            </button>
            <button
              onClick={() => router.push('/procurement')}
              className="px-6 py-2.5 bg-card border border-border text-foreground font-medium rounded-lg shadow-sm hover:bg-muted transition-colors whitespace-nowrap"
            >
              Edit All
            </button>
            <button
              onClick={handleCreateAll}
              disabled={allSuccess}
              className="px-6 py-2.5 bg-indigo-600 text-white font-medium rounded-lg shadow-sm hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors whitespace-nowrap"
            >
              {allSuccess ? 'All POs Created' : 'Create All POs at Once'}
            </button>
          </div>
        )}
      </div>



      {/* Supplier Cards */}
      <div className="space-y-6">
        {sessionData.length === 0 ? (
          <div className="text-center py-12 bg-card border border-border rounded-xl">
            <Package className="h-12 w-12 text-muted-foreground mx-auto mb-3" />
            <p className="text-muted-foreground">No pending purchase orders found in this session.</p>
          </div>
        ) : (
          sessionData.map((group, index) => {
            const statusInfo = supplierStatus[group.supplierName];
            const isSuccess = statusInfo?.status === 'success';

            // Calculate totals
            const totalItems = group.items.reduce((sum, item) => sum + item.orderQty, 0);
            const totalCost = group.items.reduce((sum, item) => sum + item.orderCost, 0);

            return (
              <div key={index} className={`bg-card border rounded-xl shadow-sm overflow-hidden transition-all duration-300 ${isSuccess ? 'border-emerald-200' : 'border-border'}`}>
                <div className={`px-6 py-4 border-b flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 ${isSuccess ? 'bg-emerald-50/50 dark:bg-emerald-900/10 border-emerald-100' : 'bg-neutral-50 dark:bg-card/30'}`}>
                  <div>
                    <h3 className="text-lg font-bold text-foreground">{group.supplierName}</h3>
                    <p className="text-sm text-muted-foreground mt-1">
                      {group.items.length} materials • {totalItems} total items • Estimated: Rs. {totalCost.toFixed(2)}
                    </p>
                  </div>

                  {isSuccess ? (
                    <div className="flex items-center gap-4">
                      <div className="flex flex-col items-end">
                        <span className="flex items-center gap-1.5 text-emerald-600 font-semibold bg-emerald-100 dark:bg-emerald-900/30 px-3 py-1.5 rounded-full text-sm">
                          <CheckCircle2 className="w-4 h-4" />
                          PO Created
                        </span>
                        {statusInfo.poNumber && (
                          <button className="flex items-center gap-1 mt-2 text-xs text-indigo-600 hover:text-indigo-800 transition-colors">
                            <ExternalLink className="w-3 h-3" />
                            View {statusInfo.poNumber}
                          </button>
                        )}
                      </div>
                      <button
                        onClick={() => setExpandedMap(prev => ({ ...prev, [group.supplierName]: !prev[group.supplierName] }))}
                        className="p-2 text-muted-foreground hover:text-foreground transition-colors rounded-full hover:bg-muted"
                        title={expandedMap[group.supplierName] === true ? "Collapse" : "Expand"}
                      >
                        {expandedMap[group.supplierName] === true ? <ChevronUp className="w-5 h-5" /> : <ChevronDown className="w-5 h-5" />}
                      </button>
                    </div>
                  ) : (
                    <div className="flex items-center gap-2">
                      <button
                        onClick={() => router.push(`/procurement?supplier=${encodeURIComponent(group.supplierName)}`)}
                        className="px-4 py-2 bg-background border border-border text-foreground font-medium rounded-lg hover:bg-muted transition-colors text-sm"
                      >
                        Edit PO
                      </button>
                      <button
                        onClick={() => router.push(`/procurement/create-po?supplier=${encodeURIComponent(group.supplierName)}`)}
                        className="px-5 py-2 bg-foreground text-background font-medium rounded-lg shadow hover:bg-neutral-800 dark:hover:bg-neutral-200 transition-colors text-sm"
                      >
                        Create PO
                      </button>
                      <button
                        onClick={() => setExpandedMap(prev => ({ ...prev, [group.supplierName]: !prev[group.supplierName] }))}
                        className="p-2 text-muted-foreground hover:text-foreground transition-colors rounded-full hover:bg-muted ml-2"
                        title={expandedMap[group.supplierName] === true ? "Collapse" : "Expand"}
                      >
                        {expandedMap[group.supplierName] === true ? <ChevronUp className="w-5 h-5" /> : <ChevronDown className="w-5 h-5" />}
                      </button>
                    </div>
                  )}
                </div>

                {expandedMap[group.supplierName] === true && (
                  <div className="p-0 overflow-x-auto">
                    <table className="w-full text-left border-collapse">
                      <thead>
                        <tr className="border-b border-border text-[11px] uppercase tracking-wider text-muted-foreground font-medium bg-muted/30">
                          <th className="px-6 py-3">Material</th>
                          <th className="px-6 py-3 text-right">Order Qty</th>
                          <th className="px-6 py-3 text-right">Est. Cost (Rs.)</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-border">
                        {group.items.map((item, idx) => (
                          <tr key={idx} className="hover:bg-muted/10 transition-colors">
                            <td className="px-6 py-3 text-sm text-foreground">
                              {item.material}
                              <div className="text-xs text-muted-foreground mt-0.5">Shortage: {item.shortage}</div>
                            </td>
                            <td className="px-6 py-3 text-sm font-medium text-foreground text-right">
                              {item.orderQty} <span className="text-xs font-normal text-muted-foreground">{item.unit}</span>
                            </td>
                            <td className="px-6 py-3 text-sm text-foreground text-right">
                              {item.orderCost.toFixed(2)}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}
              </div>
            );
          })
        )}
      </div>
    </div>
  );
}