export interface Garment {
  id: number;
  name: string;
  sku: string;
  image: string;
  size: string;
  color: string;
  stock: number;
  category: string;
  demographic: 'Men' | 'Women' | 'Kids';
  fabric: string;
  status: 'In Stock' | 'Low Stock' | 'Out of Stock';
  badgeColor: string;
  price: number;
  thirdButton: {
    text: string;
    color: string;
  };
}

export const defaultPrestitchedGarments: Garment[] = [
  // ── MEN ───────────────────────────────────────────────────────────────────
  {
    id: 1,
    name: 'Mens Casual T-Shirt',
    sku: '#TS110',
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&auto=format&fit=crop',
    size: 'S, M, L, XL, XXL',
    color: 'Grey',
    stock: 42,
    category: 'T-Shirt',
    demographic: 'Men',
    fabric: 'Cotton',
    status: 'In Stock',
    badgeColor: 'bg-[#48bb78]',
    price: 299,
    thirdButton: { text: 'Details', color: 'bg-[#1766e6] hover:bg-blue-700 text-white font-medium' },
  },
  {
    id: 2,
    name: 'Formal Mens Shirt',
    sku: '#FS422',
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500&auto=format&fit=crop',
    size: 'S, M, L, XL, XXL',
    color: 'White',
    stock: 3,
    category: 'Shirt',
    demographic: 'Men',
    fabric: 'Cotton',
    status: 'Low Stock',
    badgeColor: 'bg-[#ed8936]',
    price: 499,
    thirdButton: { text: 'Pack', color: 'bg-[#1766e6] hover:bg-blue-700 text-white font-medium' },
  },
  {
    id: 3,
    name: 'Classic Denim Jacket',
    sku: '#DJ205',
    image: 'https://images.unsplash.com/photo-1611312449412-6cefac5dc3e4?w=500&auto=format&fit=crop',
    size: 'S, M, L, XL, XXL',
    color: 'Black',
    stock: 6,
    category: 'Jacket',
    demographic: 'Men',
    fabric: 'Denim',
    status: 'Low Stock',
    badgeColor: 'bg-[#ed8936]',
    price: 1199,
    thirdButton: { text: 'Pack', color: 'bg-[#1766e6] hover:bg-blue-700 text-white font-medium' },
  },
  {
    id: 4,
    name: 'Slim Fit Chinos',
    sku: '#MC501',
    image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=500&auto=format&fit=crop',
    size: '28, 30, 32, 34, 36',
    color: 'Khaki',
    stock: 15,
    category: 'Pants',
    demographic: 'Men',
    fabric: 'Cotton Blend',
    status: 'In Stock',
    badgeColor: 'bg-[#48bb78]',
    price: 799,
    thirdButton: { text: 'Details', color: 'bg-[#1766e6] hover:bg-blue-700 text-white font-medium' },
  },
  {
    id: 5,
    name: 'Formal Trousers',
    sku: '#MT902',
    image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=500&auto=format&fit=crop',
    size: '28, 30, 32, 34, 36, 38',
    color: 'Charcoal',
    stock: 0,
    category: 'Pants',
    demographic: 'Men',
    fabric: 'Wool',
    status: 'Out of Stock',
    badgeColor: 'bg-[#e53e3e]',
    price: 999,
    thirdButton: { text: 'Restock', color: 'bg-[#e53e3e] hover:bg-red-700 text-white font-medium' },
  },
  {
    id: 6,
    name: 'Party Wear Blazer',
    sku: '#MB704',
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=500&auto=format&fit=crop',
    size: 'S, M, L, XL',
    color: 'Navy',
    stock: 8,
    category: 'Blazer',
    demographic: 'Men',
    fabric: 'Wool',
    status: 'Low Stock',
    badgeColor: 'bg-[#ed8936]',
    price: 2499,
    thirdButton: { text: 'Pack', color: 'bg-[#1766e6] hover:bg-blue-700 text-white font-medium' },
  },

  // ── WOMEN ─────────────────────────────────────────────────────────────────
  {
    id: 7,
    name: 'Traditional Silk Saree',
    sku: '#SS150',
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=500&auto=format&fit=crop',
    size: 'Free Size',
    color: 'Red',
    stock: 0,
    category: 'Saree',
    demographic: 'Women',
    fabric: 'Silk',
    status: 'Out of Stock',
    badgeColor: 'bg-[#e53e3e]',
    price: 3499,
    thirdButton: { text: 'Restock', color: 'bg-[#e53e3e] hover:bg-red-700 text-white font-medium' },
  },
  {
    id: 8,
    name: 'Womens Slim-Fit Jeans',
    sku: '#WJ303',
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=500&auto=format&fit=crop',
    size: '24, 26, 28, 30, 32',
    color: 'Blue',
    stock: 18,
    category: 'Pants',
    demographic: 'Women',
    fabric: 'Denim',
    status: 'In Stock',
    badgeColor: 'bg-[#48bb78]',
    price: 899,
    thirdButton: { text: 'Details', color: 'bg-[#1766e6] hover:bg-blue-700 text-white font-medium' },
  },
  {
    id: 9,
    name: 'Summer Sundress',
    sku: '#SD412',
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=500&auto=format&fit=crop',
    size: 'XS, S, M, L',
    color: 'Yellow',
    stock: 4,
    category: 'Dress',
    demographic: 'Women',
    fabric: 'Cotton',
    status: 'Low Stock',
    badgeColor: 'bg-[#ed8936]',
    price: 699,
    thirdButton: { text: 'Pack', color: 'bg-[#1766e6] hover:bg-blue-700 text-white font-medium' },
  },
  {
    id: 10,
    name: 'Cotton Kurta',
    sku: '#CK102',
    image: 'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?w=500&auto=format&fit=crop',
    size: 'XS, S, M, L, XL',
    color: 'Blue',
    stock: 25,
    category: 'Kurta',
    demographic: 'Women',
    fabric: 'Cotton',
    status: 'In Stock',
    badgeColor: 'bg-[#48bb78]',
    price: 599,
    thirdButton: { text: 'Details', color: 'bg-[#1766e6] hover:bg-blue-700 text-white font-medium' },
  },
  {
    id: 11,
    name: 'Hooded Sweatshirt',
    sku: '#HS809',
    image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=500&auto=format&fit=crop',
    size: 'XS, S, M, L, XL, XXL',
    color: 'Black',
    stock: 15,
    category: 'Sweatshirt',
    demographic: 'Women',
    fabric: 'Cotton Blend',
    status: 'In Stock',
    badgeColor: 'bg-[#48bb78]',
    price: 899,
    thirdButton: { text: 'Details', color: 'bg-[#1766e6] hover:bg-blue-700 text-white font-medium' },
  },
  {
    id: 12,
    name: 'Distressed Denim Shorts',
    sku: '#DS505',
    image: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=500&auto=format&fit=crop',
    size: '24, 26, 28, 30, 32',
    color: 'Light Blue',
    stock: 7,
    category: 'Shorts',
    demographic: 'Women',
    fabric: 'Denim',
    status: 'In Stock',
    badgeColor: 'bg-[#48bb78]',
    price: 499,
    thirdButton: { text: 'Details', color: 'bg-[#1766e6] hover:bg-blue-700 text-white font-medium' },
  },

  // ── KIDS ──────────────────────────────────────────────────────────────────
  {
    id: 13,
    name: 'Kids Polka Dress',
    sku: '#S0340',
    image: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=500&auto=format&fit=crop',
    size: '2Y, 3Y, 4Y, 5Y, 6Y',
    color: 'Pink',
    stock: 14,
    category: 'Dress',
    demographic: 'Kids',
    fabric: 'Cotton Blend',
    status: 'In Stock',
    badgeColor: 'bg-[#48bb78]',
    price: 399,
    thirdButton: { text: 'Details', color: 'bg-[#1766e6] hover:bg-blue-700 text-white font-medium' },
  },
  {
    id: 14,
    name: 'Kids Denim Overalls',
    sku: '#KO109',
    image: 'https://images.unsplash.com/photo-1519457431-44ccd64a579b?w=500&auto=format&fit=crop',
    size: '3Y, 4Y, 5Y, 6Y, 7Y',
    color: 'Denim',
    stock: 5,
    category: 'Overalls',
    demographic: 'Kids',
    fabric: 'Denim',
    status: 'Low Stock',
    badgeColor: 'bg-[#ed8936]',
    price: 599,
    thirdButton: { text: 'Pack', color: 'bg-[#1766e6] hover:bg-blue-700 text-white font-medium' },
  },
  {
    id: 15,
    name: 'Graphic Cartoon T-Shirt',
    sku: '#KT221',
    image: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=500&auto=format&fit=crop',
    size: '3Y, 4Y, 5Y, 6Y, 7Y, 8Y',
    color: 'Red',
    stock: 30,
    category: 'T-Shirt',
    demographic: 'Kids',
    fabric: 'Cotton',
    status: 'In Stock',
    badgeColor: 'bg-[#48bb78]',
    price: 349,
    thirdButton: { text: 'Details', color: 'bg-[#1766e6] hover:bg-blue-700 text-white font-medium' },
  },
  {
    id: 16,
    name: 'Hoodie',
    sku: '#HS810',
    image: 'https://img.freepik.com/premium-photo/white-hoodie-advertisment_1059430-107247.jpg',
    size: 'XS, S, M, L, XL, XXL',
    color: 'Black',
    stock: 8,
    category: 'Hoodie',
    demographic: 'Men',
    fabric: 'Cotton Blend',
    status: 'Low Stock',
    badgeColor: 'bg-[#ed8936]',
    price: 899,
    thirdButton: { text: 'Pack', color: 'bg-[#1766e6] hover:bg-blue-700 text-white font-medium' },
  },
];


